CREATE TABLE IF NOT EXISTS "Assets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AssetName" varchar(120) NOT NULL,
    "Category" varchar(80) NOT NULL,
    "Brand" varchar(80) NOT NULL,
    "PurchaseDate" date NOT NULL,
    "Status" varchar(20) NOT NULL CHECK ("Status" IN ('Available', 'Assigned'))
);

CREATE TABLE IF NOT EXISTS "Employees" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(120) NOT NULL,
    "Email" varchar(160) NOT NULL UNIQUE,
    "Department" varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Assignments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AssetId" integer NOT NULL REFERENCES "Assets"("Id") ON DELETE RESTRICT,
    "EmployeeId" integer NOT NULL REFERENCES "Employees"("Id") ON DELETE RESTRICT,
    "AssignedDate" date NOT NULL,
    "ReturnedDate" date NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Assignments_AssetId"
ON "Assignments" ("AssetId")
WHERE "ReturnedDate" IS NULL;
